#!/usr/bin/env python3
"""Benefactor recompiler – 68k → C translator (entry point / orchestrator).

Hard-coded for the Benefactor Amiga code region:
  - Base address $3000
  - Can read either:
      1) raw code image (file offset 0 = addr $3000), or
      2) full 512KB chip RAM dump via --chip-dump (extracts $3000..$2742D)
  - Known entry points and data regions in entries.py
  - Detects VPOSR / BZERO wait loops
  - Handles cross-function BSR/JSR correctly

Output (multi-file):
  - game.h              — all function declarations + dispatch table extern
  - game_<group>.c      — one file per group defined in entries.GROUPS
  - game_misc.c         — any functions not assigned to a named group

Sub-modules:
  helpers.py  – register/operand utilities, CC_MAP
  scanner.py  – recursive-descent function scanner
  emitter.py  – Translator class + emit_func
  entries.py  – entry-point table, name lookup, group assignment
"""
import sys, os, argparse
from capstone import *
from capstone.m68k import *

try:
    from .entries  import get_entry_addrs, get_fn_name, get_fn_group, GROUPS
    from .scanner  import collect_functions
    from .emitter  import Translator, emit_func
except ImportError:
    import importlib, pathlib
    sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))
    from recomp.entries  import get_entry_addrs, get_fn_name, get_fn_group, GROUPS  # type: ignore
    from recomp.scanner  import collect_functions                                    # type: ignore
    from recomp.emitter  import Translator, emit_func                                # type: ignore

__all__ = ['Translator', 'emit_func', 'collect_functions']


def _file_header(group_name: str) -> str:
    return (f'/* game_{group_name}.c — generated by recomp.py; do not edit by hand */\n'
            f'#include "game.h"\n'
            f'#include "recomp/hw.h"\n\n')


def main():
    parser = argparse.ArgumentParser(description='Benefactor 68k → C recompiler')
    parser.add_argument('binary')
    parser.add_argument('--chip-dump', action='store_true',
                        help='Input is full chip RAM dump; extract code slice at $3000')
    parser.add_argument('--out-dir', default='.',
                        help='Directory to write generated files into (default: .)')
    # Legacy single-file flags kept for compatibility; ignored when multi-file is active.
    parser.add_argument('--out-c', default=None, help='(ignored; use --out-dir)')
    parser.add_argument('--out-h', default=None, help='(ignored; use --out-dir)')
    # ── Second-bank (gameplay overlay) options ──────────────────────────────
    # The gameplay code is a disk overlay that overwrites the intro at the same
    # addresses. Recompiling it as a separate bank keeps both in one binary;
    # rt.c's dispatch_lookup picks the bank at runtime.
    parser.add_argument('--base', default=None, help='code base (hex), default 0x3000')
    parser.add_argument('--code-size', default=None, help='code size (hex), default 0x2442E')
    parser.add_argument('--seed', default=None,
                        help='comma-separated hex entry addrs; overrides entries.py')
    parser.add_argument('--bank', default=None,
                        help='bank name (e.g. gp); emits gfn_<bank>_<addr>, '
                             'g_fn_table_<bank>, game_<bank>_*.c, hex-only names')
    parser.add_argument('--areg', action='append', default=[],
                        help='known address-register base, e.g. --areg 5=8450 '
                             '(resolves jsr/jmp $d(aN) targets during discovery)')
    args = parser.parse_args()

    # capstone A-reg ids are M68K_REG_A0..A7 == 9..16
    areg_bases = {}
    for spec in args.areg:
        reg, val = spec.split('=')
        areg_bases[9 + int(reg)] = int(val, 16)

    base      = int(args.base, 16)      if args.base      else 0x3000
    code_size = int(args.code_size, 16) if args.code_size else 0x2442E
    bank      = args.bank
    if args.seed:
        # Allow annotated seed files: strip '#' comments per line, then split on
        # commas/whitespace. Lets gpl_seeds.txt document each indirect-dispatch
        # target while still feeding clean hex addresses to the recompiler.
        _txt = '\n'.join(ln.split('#', 1)[0] for ln in args.seed.splitlines())
        entries = [int(s, 16) for s in _txt.replace(',', ' ').split()]
    else:
        entries = get_entry_addrs()

    # Name resolver: default bank uses curated names; a secondary bank uses
    # prefixed hex-only names so symbols never collide with the intro bank.
    if bank:
        cname = lambda a: f'{bank}_{a:06X}'
    else:
        cname = get_fn_name

    with open(args.binary, 'rb') as f:
        raw = f.read()

    if args.chip_dump:
        if len(raw) < base + code_size:
            raise SystemExit(
                f'chip dump too small: need at least 0x{base + code_size:X} bytes, '
                f'got 0x{len(raw):X}')
        data = raw[base:base + code_size]
    else:
        data = raw

    md = Cs(CS_ARCH_M68K, CS_MODE_M68K_000 | CS_MODE_BIG_ENDIAN)
    md.detail = True

    funcs = collect_functions(data, base, entries, md, areg_bases=areg_bases)
    print(f'Collected {len(funcs)} functions')

    translator = Translator(set(funcs.keys()))

    out_dir = args.out_dir
    os.makedirs(out_dir, exist_ok=True)

    sorted_addrs = sorted(funcs.keys())

    if bank:
        # ── Secondary bank (gameplay overlay) ────────────────────────────────
        # All functions are auto-discovered (no curated groups), so chunk them
        # across several .c files to keep translation units reasonable. Symbols
        # are gfn_<bank>_<addr>; table is g_fn_table_<bank>.
        count_macro = f'GAME_{bank.upper()}_FN_COUNT'
        table_name  = f'g_fn_table_{bank}'
        h_path = os.path.join(out_dir, f'game_{bank}.h')
        with open(h_path, 'w') as h:
            h.write(f'/* game_{bank}.h — generated by recomp.py --bank {bank}; do not edit */\n')
            h.write('#pragma once\n#include "recomp/rt.h"\n#include "recomp/hw.h"\n\n')
            for a in sorted_addrs:
                h.write(f'void gfn_{cname(a)}(M68KCtx *ctx); /* ${a:06X} */\n')
            h.write(f'\n#define {count_macro} {len(funcs)}\n')
            h.write(f'extern const GameFnEntry {table_name}[{count_macro}];\n')

        CHUNK = 500
        chunks = [sorted_addrs[i:i+CHUNK] for i in range(0, len(sorted_addrs), CHUNK)] or [[]]
        written_files = []
        for ci, addrs in enumerate(chunks):
            fname = f'game_{bank}_{ci}.c'
            with open(os.path.join(out_dir, fname), 'w') as c:
                c.write(f'/* {fname} — generated by recomp.py --bank {bank}; do not edit */\n')
                c.write(f'#include "generated/game_{bank}.h"\n\n')
                for a in addrs:
                    emit_func(c, a, funcs[a], translator, cname=cname)
            written_files.append(fname)
            print(f'  {fname}: {len(addrs)} function(s)')

        # Dispatch table in its own file.
        tfname = f'game_{bank}_table.c'
        with open(os.path.join(out_dir, tfname), 'w') as c:
            c.write(f'#include "generated/game_{bank}.h"\n\n')
            c.write(f'const GameFnEntry {table_name}[{count_macro}] = {{\n')
            for a in sorted_addrs:
                c.write(f'  {{ 0x{a:06X}u, gfn_{cname(a)} }},\n')
            c.write('};\n')
            c.write(f'const int g_fn_{bank}_count = {count_macro};\n')
        written_files.append(tfname)
        print(f'Wrote {h_path}')
        print(f'Wrote {len(written_files)} source file(s)')
        return

    # ── Header ──────────────────────────────────────────────────────────────
    h_path = os.path.join(out_dir, 'game.h')
    with open(h_path, 'w') as h:
        h.write('/* game.h — generated by recomp.py; do not edit by hand */\n')
        h.write('#pragma once\n')
        h.write('#include "recomp/rt.h"\n\n')
        for a in sorted_addrs:
            name  = get_fn_name(a)
            group = get_fn_group(a)
            h.write(f'void gfn_{name}(M68KCtx *ctx); /* ${a:06X}  [{group}] */\n')
        h.write(f'\n#define GAME_FN_COUNT {len(funcs)}\n')
        h.write('extern const GameFnEntry g_fn_table[GAME_FN_COUNT];\n')

    # ── Source files (one per group) ─────────────────────────────────────────
    # Assign each function to its group.
    all_groups = list(GROUPS) + ['misc']
    group_funcs: dict[str, list] = {g: [] for g in all_groups}
    for a in sorted_addrs:
        g = get_fn_group(a)
        if g not in group_funcs:
            g = 'misc'
        group_funcs[g].append(a)

    written_files = []
    for g in all_groups:
        addrs = group_funcs[g]
        # 'discovered' is always emitted (even empty) because CMake references
        # game_discovered.c unconditionally; other empty groups are skipped.
        if not addrs and g != 'discovered':
            continue
        fname = f'game_{g}.c'
        fpath = os.path.join(out_dir, fname)
        with open(fpath, 'w') as c:
            c.write(_file_header(g))
            for a in addrs:
                emit_func(c, a, funcs[a], translator)
        written_files.append(fname)
        print(f'  {fname}: {len(addrs)} function(s)')

    # ── Dispatch table (appended to game_loop.c, or game_misc.c as fallback) ──
    table_group = 'loop' if group_funcs.get('loop') else 'misc'
    table_fname = f'game_{table_group}.c'
    table_fpath = os.path.join(out_dir, table_fname)
    with open(table_fpath, 'a') as c:
        c.write('const GameFnEntry g_fn_table[GAME_FN_COUNT] = {\n')
        for a in sorted_addrs:
            name = get_fn_name(a)
            c.write(f'  {{ 0x{a:06X}u, gfn_{name} }},\n')
        c.write('};\n')

    print(f'Wrote {h_path}')
    print(f'Wrote {len(written_files)} source file(s): {", ".join(written_files)}')
    print(f'Dispatch table appended to {table_fname}')


if __name__ == '__main__':
    main()
